### ISSUE TITLE
Playing quiz, is not an UI thing

### ISSUE THREAD

**Issue by mayisa87** [mduffy023/QuizApp#26]
https://github.com/mduffy023/QuizApp/blob/13ccee7a0bfa999688f5c751cf2d8ea60a6afd3b/UIMethods.cs#L165-L184

This method is not an UI method.  You should split up your methods better into smaller logical parts.

Playing the quiz, so starting it, is a Logic thing. So there should be a Logic method "StartAQuiz", as parameter you can give a Quiz for example.

There you can then loop through questions and check on answers from user. But as the playing itself is a logic method, things like 
https://github.com/mduffy023/QuizApp/blob/13ccee7a0bfa999688f5c751cf2d8ea60a6afd3b/UIMethods.cs#L172-L173
have to be a seprated UI method, like "GetAnswerFromUser" .

[Or ](https://github.com/mduffy023/QuizApp/blob/13ccee7a0bfa999688f5c751cf2d8ea60a6afd3b/UIMethods.cs#L176

Can be one method like "OutputRightAnswerMessage"

Currently you have all of your logic in the UIMethods

**Comment by mduffy023** [comment]
I've split that method between Logic and UI classes
