### ISSUE TITLE
Write methods, still separate into different classes

### ISSUE THREAD

**Issue by mayisa87** [mduffy023/QuizApp#3]
https://github.com/mduffy023/QuizApp/blob/56c7363d9a0597b3a5645f558b01e64b7a8da18d/Program.cs#L15-L20

This block could be an UI method, checking id user wants to add another question and return a bool then.

Ans take care about sequence od doing your code. You first create an question object and add it to the list immediately. Then you ask if user wants to create a question. Better first ask user and only create an object if needed.

And do some introduction text and output, it's strange that the user gets as first message "Do you want to add another method?"

**Comment by mduffy023** [comment]
fixed this issue forgot to close it
