### ISSUE TITLE
Move UI parts out of logic and separate logic from data

### ISSUE THREAD

**Issue by mayisa87** [mduffy023/QuizApp#5]
https://github.com/mduffy023/QuizApp/blob/56c7363d9a0597b3a5645f558b01e64b7a8da18d/Quiz.cs#L37

Currently you got this Quiz class holding a list of questions,  that's OK.

But in general a data class should not include logic like playing the Quiz and calling UI stuff. A Data class like your Question or Quiz only holds fields and operations on fields.

So you should introduce a separated logic class and in there you can have a method like "PlayQuiz(Quiz quizToPlay)"

The you have in there the code to output all of your a answers and also the question.  This is pure UI stuff. So write a method like "DisplayQuestionAndAnswers" e.g. only doing the output 
And then one method, reading inout from user and returning to your logic method the answer entered for further checks

**Comment by mduffy023** [comment]
fixed this issue forgot to close
